#!/bin/sh

export HISTSIZE=10000000
export SAVEHIST=10000000
export PATH="$HOME/.local/bin":$PATH
export PATH="/usr/local/sbin":$PATH

# additional paths
export PATH="$HOME/.scripts":$PATH
export PATH="$HOME/.dotcube/bin":$PATH
export PATH="$HOME/.dotcube/bin":$PATH
export PATH="$HOME/.config/zsh/plugins/fzf/bin":$PATH

# locale fix for starship/zsh autocomplete char duplication bug
case "$(uname)" in
    "Linux")
        export LC_CTYPE=C.utf8
        ;;
    "Darwin")
        export LC_CTYPE=en_US.UTF-8
        ;;
esac
