#!/bin/zsh
function zsh_add_file() {
    [ -f "$ZDOTDIR_REPO/$1" ] && source "$ZDOTDIR_REPO/$1"
}

function zsh_add_file_local() {
    [ -f "$ZDOTDIR_LOCAL/$1" ] && source "$ZDOTDIR_LOCAL/$1"
}

function zsh_add_extra_files() {
    [ -f $1 ] && source "$1"
}

function zsh_add_plugin() {
    PLUGIN_NAME=$(echo $1 | cut -d "/" -f 2)
    if [ -d "$ZDOTDIR_LOCAL/plugins/$PLUGIN_NAME" ]; then 
        zsh_add_file_local "plugins/$PLUGIN_NAME/$PLUGIN_NAME.plugin.zsh" || \
        zsh_add_file_local "plugins/$PLUGIN_NAME/$PLUGIN_NAME.zsh"
        if [ $2 ]; then
            for f in $ZDOTDIR_LOCAL/plugins/$PLUGIN_NAME/$~2; do 
                zsh_add_extra_files $f; 
            done
        fi
    else
        git clone "https://github.com/$1.git" "$ZDOTDIR_REPO/plugins/$PLUGIN_NAME"
    fi
}

function zsh_add_theme() {
    THEME_NAME=$(echo $1 | cut -d "/" -f 2)
    if [ -d "$ZDOTDIR_REPO/themes/$THEME_NAME" ]; then
        zsh_add_file "themes/$THEME_NAME/$THEME_NAME.zsh-theme"
    else
        git clone "https://github.com/$1.git" "$ZDOTDIR_REPO/themes/$THEME_NAME"
    fi
}

function zsh_add_completion() {
    GIT_NAME=$(echo $1 | cut -d "/" -f 1-2)
    PLUGIN_NAME=$(echo $1 | cut -d "/" -f 2)
    COMP_PATH=$(echo $1 | cut -d "/" -f 3-6)
    if [ ! -z $COMP_PATH ]; then
        COMP_PATH=/$COMP_PATH
    fi
    if [ -d "$ZDOTDIR_REPO/plugins/$PLUGIN_NAME" ]; then 
        # For completions
		completion_file_path=$(ls $ZDOTDIR_REPO/plugins/$PLUGIN_NAME$COMP_PATH/_*)
		fpath+="$(dirname "${completion_file_path}")" 2>/dev/null #route errors to devnull for osx
        zsh_add_file "plugins/$PLUGIN_NAME/$PLUGIN_NAME.plugin.zsh"
    else
        git clone "https://github.com/$GIT_NAME.git" "$ZDOTDIR_REPO/plugins/$PLUGIN_NAME"
		fpath+=$(ls $ZDOTDIR_REPO/plugins/$PLUGIN_NAME$COMP_PATH/_*)
        [ -f $ZDOTDIR_REPO/.zccompdump ] && $ZDOTDIR_REPO/.zccompdump
    fi
	completion_file="$(basename "${completion_file_path}")"
	if [ "$2" = true ] && compinit "${completion_file:1}"
}
