---
- name: "ZSH | Check if first run"
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.dotcube.run"
  register: dotcube_run

#create the .config folder if it doesn't exist
- name: "ZSH | Create .config folder"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config"
    state: directory
  when: dotcube_run.stat.exists == false
  changed_when: false

- name: "ZSH | Backing up the original shell to a file"
  ansible.builtin.copy:
    content: "{{ ansible_env.SHELL }}"
    dest: "{{ ansible_user_dir }}/.config/.dotcube_original_shell"
    force: yes
  when: dotcube_run.stat.exists == false
  changed_when: false

- name: "ZSH | Copy .dotcube folder"
  ansible.posix.synchronize:
    src: "{{ lookup('env', 'HOME') }}/.dotcube"
    dest: "{{ ansible_user_dir }}"
  when: called_from == 'remote'
  changed_when: false

- name: "ZSH | Install zsh plugins/completions"
  git:
    repo: "{{ item.repo }}{{ item.project }}.git"
    dest: "{{ ansible_user_dir }}/.config/zsh/plugins/{{ item.project }}"
    clone: yes
    update: yes
    force: yes
  loop: "{{ zsh_plugin_repos }}"

- name: "ZSH | Check if .zshrc is a symlink"
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.zshrc"
  register: zshrc

- name: "ZSH | Backup .zshrc"
  ansible.builtin.shell: mv {{ ansible_user_dir }}/.zshrc {{ ansible_user_dir }}/.zshrc.bak
  args:
    warn: no
  when: zshrc.stat.islnk == false
  ignore_errors: true

- name: "ZSH | Create symlink for zshrc"
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/.dotcube/dotfiles/zsh/zshrc"
    dest: "{{ ansible_user_dir }}/.zshrc"
    state: link
    force: yes
    follow: false

- name: "ZSH | Set default terminal"
  user:
    name: "{{ host_user }}"
    shell: /bin/zsh
  become: true

