#!/bin/sh
export ZDOTDIR=$HOME/.config/zsh
export ZDOTDIR_REPO=$HOME/.dotcube/dotfiles/zsh
HISTFILE=~/.zsh_history
setopt appendhistory

# some useful options (man zshoptions)
setopt autocd extendedglob nomatch automenu
setopt interactive_comments
stty stop undef		# Disable ctrl-s to freeze terminal.
zle_highlight=('paste:none')

# beeping is annoying
unsetopt BEEP

# completions
autoload -Uz compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
# zstyle ':completion::complete:lsof:*' menu yes select
zmodload zsh/complist
# compinit
_comp_options+=(globdots)		# Include hidden files.

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

# Colors
autoload -Uz colors && colors

# Useful Functions
source "$ZDOTDIR_REPO/zsh-config/zsh-functions"

# Load options
zsh_add_file "zsh-config/zsh-options"

# Normal files to source
zsh_add_file "zsh-config/zsh-exports"
zsh_add_file "zsh-config/zsh-aliases"
zsh_add_file "zsh-config/zsh-local"

# Plugins
zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
zsh_add_plugin "zsh-users/zsh-history-substring-search"
zsh_add_plugin "hlissner/zsh-autopair" "autopair.zsh"
zsh_add_plugin "junegunn/fzf" "shell/*.zsh"

zsh_add_completion "zsh-users/zsh-completions/src" true

# Key-bindings
case "$(uname -s)" in

Linux)
    # echo 'Linux'
    bindkey '^[[A' history-substring-search-up
    bindkey '^[[B' history-substring-search-down
	;;

Darwin)
	# echo 'Mac OS X'
    bindkey '^[[A' history-substring-search-up
    bindkey '^[[B' history-substring-search-down
	;;

esac

# Load extras
zsh_add_file "zsh-config/zsh-loadextras"

# Init prompt
zsh_add_file "zsh-config/zsh-prompt"

# Load custom zsh config post-prompt
if [ -f "$ZDOTDIR/zsh-custom" ]; then
    zsh_add_file "$ZDOTDIR/zsh-custom"
fi