---
- name: "GITHUB-COPILOT | Update APT Repos"
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: "GITHUB-COPILOT | Install gh package"
  ansible.builtin.apt:
    name: gh
    update_cache: yes
    state: present
  become: true

- name: "GITHUB-COPILOT | Check nodejs version"
  ansible.builtin.command: node -v
  register: node_version
  become: true
  changed_when: false

- name: "GITHUB-COPILOT | Uninstall nodejs"
  ansible.builtin.apt:
    name: 
     - nodejs
     - libnode72
     - libnode-dev
    state: absent
  when: node_version.stdout.find('v18') == -1
  become: true

- name: "GITHUB-COPILOT | Add nodesource repository"
  ansible.builtin.command: curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
  become: true
  when: node_version.stdout.find('v18') == -1

- name: "GITHUB-COPILOT | Install nodejs"
  ansible.builtin.apt:
    name: nodejs
    update_cache: yes
    state: present
  become: true
  when: node_version.stdout.find('v18') == -1

- name: "GITHUB-COPILOT | Install github-copilot-cli via npm"
  ansible.builtin.npm:
    name: "@githubnext/github-copilot-cli"
    global: yes
    state: present
  become: true


